# Form implementation generated from reading ui file 'delete_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        Dialog.setMinimumSize(QtCore.QSize(320, 240))
        Dialog.setMaximumSize(QtCore.QSize(320, 240))
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(11, 10, 301, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TextDeialog = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextDeialog.sizePolicy().hasHeightForWidth())
        self.TextDeialog.setSizePolicy(sizePolicy)
        self.TextDeialog.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.TextDeialog.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TextDeialog.setWordWrap(True)
        self.TextDeialog.setObjectName("TextDeialog")
        self.verticalLayout.addWidget(self.TextDeialog)
        self.ButtonsDialog = QtWidgets.QDialogButtonBox(parent=self.verticalLayoutWidget)
        self.ButtonsDialog.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ButtonsDialog.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.ButtonsDialog.setCenterButtons(True)
        self.ButtonsDialog.setObjectName("ButtonsDialog")
        self.verticalLayout.addWidget(self.ButtonsDialog)

        self.retranslateUi(Dialog)
        self.ButtonsDialog.accepted.connect(Dialog.accept) # type: ignore
        self.ButtonsDialog.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Вы уверены?"))
        self.TextDeialog.setText(_translate("Dialog", "ТЕКСТ"))
